title: Srikanth Bolla
author: Srikanth Bolla
subtitle: Code, Curiosities, and the Occasional Deep Dive

url: "https://skbol.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/skbol/"
footer_text: "Hosted on GitHub"

profile-picture: assets/skbol/img/profile.png
favicon_location: assets/skbol/favicon/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "/about"
   link: "about"
 - name: "/resume"
   absolute-link: "assets/skbol/img/profile.png"
 - name: "/linkedIn"
   absolute-link: "https://www.linkedin.com/in/srikanthbolla/"

markdown: kramdown
highlighter: rouge
    input: GFM
